version: "3.1"

networks:
  microservices:
    driver: bridge
services:
  discovery-service:
    image: nu.westlin.microservices/discovery-service:latest
    networks:
      microservices:
        aliases:
          - discovery-service
    ports:
      - 3000:3000

  order-service:
    image: nu.westlin.microservices/order-service:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:3000/eureka/
    networks:
      microservices:
        aliases:
          - order-service
    expose:
      - 3001
    depends_on:
      - discovery-service

  customer-service:
    image: nu.westlin.microservices/customer-service:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:3000/eureka/
    networks:
      microservices:
        aliases:
          - customer-service
    expose:
      - 3002
    depends_on:
      - discovery-service

  gateway-service:
    image: nu.westlin.microservices/gateway-service:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:3000/eureka/
    networks:
      microservices:
        aliases:
          - gateway-service
    ports:
      - 8090:8090
    depends_on:
      - discovery-service

  web:
    image: nu.westlin.microservices/web:latest
    environment:
      - api.rooUri=http://gateway-service:8090/api
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:3000/eureka/
    networks:
      microservices:
        aliases:
          - web
    ports:
      - 8080:8080
    depends_on:
      - gateway-service
